apiVersion: v1
data:
  custom_parsers.conf: |
    [PARSER]
        Name docker_no_time
        Format json
        Time_Keep Off
        Time_Key time
        Time_Format %Y-%m-%dT%H:%M:%S.%L

    [PARSER]
        Name nginx_access
        Format regex
        Regex ^(?<remote>[^ ]*) - (?<user>[^ ]*) \[(?<time>[^\]]*)\] "(?<method>\S+) (?<uri>\S+) (?<protocol>\S+)" (?<status>\d+) (?<size>\d+) "(?<referrer>[^\"]*)" "(?<agent>[^\"]*)"
        Time_Key time
        Time_Format %d/%b/%Y:%H:%M:%S %z

    [PARSER]
        Name nginx_error
        Format regex
        Time_Key time
        Time_Format %Y/%m/%d %H:%M:%S
  fluent-bit.conf: |
    [SERVICE]
        Daemon Off
        Flush 1
        Log_Level info
        Parsers_File /fluent-bit/etc/parsers.conf
        Parsers_File /fluent-bit/etc/conf/custom_parsers.conf
        HTTP_Server On
        HTTP_Listen 0.0.0.0
        HTTP_Port 2020
        Health_Check On

    [INPUT]
        Name tail
        Path /var/log/containers/*.log
        multiline.parser docker, cri
        Tag kube.*
        Mem_Buf_Limit 5MB
        Skip_Long_Lines On

    [INPUT]
        Name systemd
        Tag host.*
        Systemd_Filter _SYSTEMD_UNIT=kubelet.service
        Read_From_Tail On

    [INPUT]
        Name tail
        Path /host/var/log/nginx/access.log
        Tag nginx.access
        Parser nginx_access
        DB /var/log/flb_nginx_access.db
        Mem_Buf_Limit 5MB
        Skip_Long_Lines On

    [INPUT]
        Name tail
        Path /host/var/log/nginx/error.log
        Tag nginx.error
        Parser nginx_error
        DB /var/log/flb_nginx_error.db
        Mem_Buf_Limit 5MB
        Skip_Long_Lines On

    [FILTER]
        Name kubernetes
        Match kube.*
        Merge_Log On
        Keep_Log Off
        K8S-Logging.Parser On
        K8S-Logging.Exclude On

    [OUTPUT]
        Name opensearch
        Match kube.*
        Host my-first-cluster.default.svc.cluster.local
        Port 9200
        TLS On
        TLS.Verify Off
        HTTP_User admin
        HTTP_Passwd admin
        Index fluentbit-logs
        Suppress_Type_Name On
        Logstash_Format On
        Retry_Limit False
        Trace_Error On
        Trace_Output On

    [OUTPUT]
        Name opensearch
        Match host.*
        Host my-first-cluster.default.svc.cluster.local
        Port 9200
        TLS On
        TLS.Verify Off
        HTTP_User admin
        HTTP_Passwd admin
        Index fluentbit-logs-%Y.%m.%d
        Suppress_Type_Name On
        Logstash_Format Off
        Retry_Limit False
        Trace_Error On
        Trace_Output On

    [OUTPUT]
        Name opensearch
        Match nginx.access
        Host my-first-cluster.default.svc.cluster.local
        Port 9200
        TLS On
        TLS.Verify Off
        HTTP_User admin
        HTTP_Passwd admin
        Index nginx-access
        Suppress_Type_Name On
        Logstash_Format Off
        Retry_Limit False
        Trace_Error On
        Trace_Output On

    [OUTPUT]
        Name opensearch
        Match nginx.error
        Host my-first-cluster.default.svc.cluster.local
        Port 9200
        TLS On
        TLS.Verify Off
        HTTP_User admin
        HTTP_Passwd admin
        Index nginx-error
        Suppress_Type_Name On
        Logstash_Format Off
        Retry_Limit False
        Trace_Error On
        Trace_Output On
kind: ConfigMap
metadata:
  annotations:
    meta.helm.sh/release-name: fluent-bit
    meta.helm.sh/release-namespace: fluent
  creationTimestamp: "2025-06-10T13:48:26Z"
  labels:
    app.kubernetes.io/instance: fluent-bit
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: fluent-bit
    app.kubernetes.io/version: 4.0.3
    helm.sh/chart: fluent-bit-0.49.1
  name: fluent-bit
  namespace: fluent
  resourceVersion: "56349"
  uid: 762e7910-4df0-4ceb-ac8e-14618cbe1c64
